/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_michaeldelrosario_nativesensors_NativeSensorsJNI */

#ifndef _Included_com_michaeldelrosario_nativesensors_NativeSensorsJNI
#define _Included_com_michaeldelrosario_nativesensors_NativeSensorsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_michaeldelrosario_nativesensors_NativeSensorsJNI
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_michaeldelrosario_nativesensors_NativeSensorsJNI_nativeFree
  (JNIEnv *, jclass);

/*
 * Class:     com_michaeldelrosario_nativesensors_NativeSensorsJNI
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_michaeldelrosario_nativesensors_NativeSensorsJNI_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_michaeldelrosario_nativesensors_NativeSensorsJNI
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_michaeldelrosario_nativesensors_NativeSensorsJNI_nativeStart
  (JNIEnv *, jclass);

/*
 * Class:     com_michaeldelrosario_nativesensors_NativeSensorsJNI
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_michaeldelrosario_nativesensors_NativeSensorsJNI_nativeStop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
